		<!-- FOOTER -->
		<section class="footer pt-6" id="footer1-2">

			<div class="container">
				<div class="media-container-row content text-light">
					<div class="col-12 col-md-2">
						<div class="media-wrap">
							<a href="#/">
								<img src="assets/images/head-flame.png" alt="Wild Jr's">
							</a>
						</div>
					</div>
					<div class="col-12 col-md-5 mbr-fonts-style">
						<h2 class="pb-3 text-orange">
							Contact Us
						</h2>
						<p class="footer-links">
							Email: info@prosauces.com
						</p>
					</div>
					<div class="col-12 col-md-2 mbr-fonts-style no-margin">
						<h2 class="pb-3 text-orange">
							Links
						</h2>
						
						<p class="footer-links mb-0">
							<a class="text-primary" href="index.php">Home</a><br/>
							<a class="text-primary" href="store.php">Store</a><br/>
							<a class="text-primary" href="testimonials.php">Testimonials</a><br/>
							<!--<a class="text-primary" href="#/">Merchandise</a><br/>-->
							<!--<a class="text-primary" href="#/">Friends</a>-->
						</p>
					</div>
					<div class="col-12 col-md-3 mbr-fonts-style">
						<h2 class="pb-md-3 d-none d-md-block">&nbsp;
						</h2>
						<p class="footer-links">
							<a class="text-primary" href="recipes.php">Recipes</a><br/>
							<a class="text-primary" href="faqs.php">FAQs</a><br/>
							<a class="text-primary" href="about.php">About</a><br/>
							<!--<a class="text-primary" href="#/">Contact</a>-->
						</p>
					</div>
				</div>
				<div class="footer-lower">
					<div class="media-container-row">
						<div class="col-sm-12">
							<hr>
						</div>
					</div>
					<div class="media-container-row mbr-white">
						<div class="col-12 col-sm-7 copyright">
							<p class="footer-links mbr-fonts-style copyright">
								© Copyright <?php echo date("Y"); ?> WD Reese, LLC - All Rights Reserved
							</p>
						</div>
						<div class="col-12 col-sm-5">
							<div class="social-list align-right">
								<div class="soc-item">
									<a href="https://twitter.com/wildjrhotsauce" target="_blank">
										<i class="socicon-twitter fa fa-twitter fa-2x"></i>
									</a>
								</div>
								<div class="soc-item">
									<a href="https://www.facebook.com/Wild-Jrs-Hot-Sauce-1520417508101041" target="_blank">
										<i class="socicon-facebook fa fa-facebook fa-2x"></i>
									</a>
								</div>
								<div class="soc-item">
									<a href="https://www.instagram.com/wildjrhotsauce/" target="_blank">
										<i class="socicon-instagram fa fa-instagram fa-2x"></i>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		
