<!DOCTYPE html>
<html>

	<head>
		<!-- Site made with Mobirise Website Builder v4.9.7, # -->
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
		<link rel="shortcut icon" href="assets/images/navbar-logo-circle.png" type="image/x-icon">
		<meta name="description" content="">

		<title>Wild Jr's Hot Sauce :: Don't fear the sauce!</title>
		<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
		<link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
		<!--<link rel="stylesheet" href="assets/socicon/css/styles.css">-->
		<link rel="stylesheet" href="assets/theme/css/font-awesome.min.css">
		<link rel="stylesheet" href="assets/dropdown/css/style.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="assets/theme/css/custom.css">
		<link rel="stylesheet" href="assets/theme/css/animate.css">
	</head>

	<body>
		<section class="menu" once="menu" id="menu1-0">
			<!--<div class="navbar box-shadow navbar-dropdown navbar-fixed-top">-->
			<nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
				<div class="container d-flex justify-content-between">
					<div class="menu-logo">
						<div class="navbar-brand">
							<span class="navbar-logo">
								<a href="index.php">
									<img src="assets/images/navbar-logo.png" alt="Wild Jr's">
								</a>
							</span>
						</div>
					</div>
					<div class="menu-buttons">
						<a class="nav-button"><span id="nav-icon3"><span></span><span></span><span></span><span></span></span></a>

						<div data-layout="MEDIUM_ICON_COUNTER" data-custom-icon-url="assets/images/shopping-cart.-reverse.svg" class="ec-cart-widget"></div>
						<div>
							<script data-cfasync="false" type="text/javascript" src="https://app.ecwid.com/script.js?17415697&data_platform=code&data_date=2019-08-11" charset="utf-8"></script>
							<script type="text/javascript">Ecwid.init();</script>
						</div>
					</div>
				</div>
			</nav>
			<!--</div> navbar end-->

			<div class="fixed-top main-menu">
				<div class="p-5">
					<ul class="nav flex-column">
						<li class="nav-item delay-1"><a class="nav-link" href="index.php">Home</a></li>
						<li class="nav-item delay-1"><a class="nav-link" href="store.php">Store</a></li>
						<li class="nav-item delay-1"><a class="nav-link" href="testimonials.php">Testimonials</a></li>
						<li class="nav-item delay-1"><a class="nav-link" href="recipes.php">Recipes</a></li>
						<li class="nav-item delay-1"><a class="nav-link" href="faqs.php">FAQs</a></li>
						<li class="nav-item delay-1"><a class="nav-link" href="about.php">About</a></li>
					</ul>
				</div>
			</div> <!--main-menu end-->
		</section>

<!-- START HEADER -->	
<!-- END HEADER -->